[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  PUPPETEER_EXECUTABLE_PATH ="/opt/build/repo/node_modules/chromium/lib/chromium/chrome-linux/chrome"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["puppeteer-core", "chrome-aws-lambda"]
