name: Build, Push to Staging, and Deploy

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          export BUN_INSTALL="$HOME/.bun"
          export PATH="$BUN_INSTALL/bin:$PATH"

      - name: Install dependencies
        run: bun install

      - name: Update Version
        run: bash scripts/update-version.sh

      - name: Build Next.js app
        run: bun run build

      - name: Push to Staging Branch
        if: success()
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout staging
          git merge ${{ github.ref_name }} --no-ff
          git push origin staging

      - name: Deploy to Vercel
        if: success()
        run: vercel --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
