name: Build, Push to Staging, and Deploy

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Set up Bun
        run: |
          npm i -g bun

      - name: Install dependencies
        run: bun install
      
      - name: Install dotenv-cli
        run: bun add dotenv-cli

      - name: Load Environment Variables
        run: dotenv -e .env -- bun run build

      - name: Update Version
        run: bash scripts/update-version.sh

      - name: Build Next.js app
        run: npm run build

      - name: Push to Staging Branch
        if: success()
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout staging
          git merge ${{ github.ref_name }} --no-ff
          git push origin staging

      - name: Deploy to Vercel
        if: success()
        run: vercel --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
